version: '3'

networks:
  gateway:
    driver: overlay

services:
  nginx:
    depends_on:
      - web_ui
    image: nginx
    networks:
      - gateway
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/cert:/etc/nginx/cert:ro


  web_ui:
    build:
      context: ./web_ui
      args:
        NPM_REGISTRY: https://registry.npm.taobao.org
        FRONT_REPO: https://gitee.com/JoverSite/web-front
        BACK_REPO: https://gitee.com/JoverSite/web-back
        FRONT_BRANCH: package
        BACK_BRANCH: dev
    networks:
      - gateway
    command: ["--port", "8080"]
