version: '3'

networks:
  gateway:
    driver: overlay

volumes:
  nginx_conf: ./nginx/default.conf
  nginx_cert: ./nginx/cert

services:
  nginx:
    depends_on:
      - web_ui
    image: nginx
    container_name: nginx
    networks:
      - gateway
    ports:
      - 80:80
    volumes:
      - nginx_conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_cert:/etc/nginx/cert:ro


  web_ui:
    build:
      context: ./web_ui
      args:
        NPM_REGISTRY: https://registry.npm.taobao.org
        FRONT_REPO: https://gitee.com/JoverSite/web-front
        BACK_REPO: https://gitee.com/JoverSite/web-back
        FRONT_BRANCH: package
        BACK_BRANCH: dev
    container_name: web_ui
    networks:
      - gateway
    command: ["--port", "8080"]
