version: '3'

networks:
  gateway:
    driver: overlay

volumes:
  static_files:

services:
  nginx:
    depends_on:
      - web_ui
    image: nginx
    networks:
      - gateway
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./nginx/cert:/etc/nginx/cert:ro
      - static_files:/static:ro


  web_ui:
    image: web_ui
    networks:
      - gateway
    volumes:
      - static_files:/www/src/static
    command: ["--port", "8080"]
